#!/bin/sh
set -e

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/bash
# mkdir -p "$XDG_CONFIG_HOME"/alacritty/themes
mkdir -p "$XDG_CONFIG_HOME"/skhd
mkdir -p "$XDG_CONFIG_HOME"/k9s

# create symbolic links

ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/tmux/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/alacritty/alacritty.toml" "$XDG_CONFIG_HOME"/alacritty/alacritty.toml
ln -sf "$PWD/newsboat/config" "$HOME"/.newsboat/config
ln -sf "$PWD/newsboat/urls" "$HOME"/.newsboat/urls
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/scripts" "$HOME/Scripts"
ln -sf "$PWD/skhd/skhdrc" "$XDG_CONFIG_HOME"/skhd/skhdrc

# set up alacritty
#git clone https://github.com/rose-pine/alacritty.git
#cp ./alacritty/dist/* ~/$XDG_CONFIG_HOME/alacritty
#rm -r ./alacritty

# Second Brain
# This one's a little tricky because the path contains a space. It needs to be stored as an array,
# and when called it needs to be quoted.
# export SECOND_BRAIN=("/Users/cyrilghali/Library/Mobile Documents/iCloud~md~obsidian/Documents/second-brain-01-07-23")
# iCloud
export ICLOUD=("/Users/cyrilghali/Library/Mobile Documents/com~apple~CloudDocs")
ln -sf "$ICLOUD" ~/icloud
