#!/usr/bin/env bash
# Increases the magnifier rate up to a defined maximum
set -e

maxValue=4.0

# the gnome desktop entry to be updated
key="org.gnome.desktop.a11y.magnifier mag-factor"
current=$(gsettings get $key)
step=0.2
newValue=$(echo "$current + $step" | bc -l)

# same as: rate=min(current+step, maxValue)
if (( $(echo "$newValue < $maxValue" | bc -l) ))
then
  echo "Zoom level must be increased to $newValue";
else
  newValue=$maxValue
  echo "Zoom level must be set to its max value: $maxValue"
fi
output=$(gsettings set $key $newValue)

