#!/usr/bin/env bash
# Decreases the magnifier level down to a defined minimum

minValue=1.0

# the gnome desktop entry holding the zoom rate
key="org.gnome.desktop.a11y.magnifier mag-factor"
current=$(gsettings get $key)

# same as: rate=max(current-step, minValue)
step=0.2
newValue=$(echo "$current - $step" | bc -l)
if (( $(echo "$newValue > $minValue" | bc -l) ))
then
  echo "Zoom level must be decreased to $newValue";
else
  newValue=$minValue
  echo "Zoom level must be set to its min value: $minValue"
fi
output=$(gsettings set $key $newValue)

